version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: asset_db
      POSTGRES_USER: asset_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"