sonar.projectKey=vilart_asset_management
sonar.organization=vilart

sonar.python.version=3.12
sonar.sources=.

sonar.exclusions=**/migrations/**, **/venv/**, **/staticfiles/**, manage.py, **/*.html
sonar.coverage.exclusions=config/asgi.py, config/wsgi.py, manage.py, **/migrations/**
sonar.python.coverage.reportPaths=coverage.xml