# Generated by Django 6.0.2 on 2026-03-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_historicalasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="additional_info",
            field=models.TextField(blank=True, default="t"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="additional_info",
            field=models.TextField(blank=True, default="t"),
            preserve_default=False,
        ),
    ]
