name: Django CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout from repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 2. Check with gitleaks
      uses: gitleaks/gitleaks-action@v2@8d1f98c7967eb1e79cb44ac6241a124e145d2165
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 3. Generating .env file
      run: |
        echo "SECRET_KEY=super-secret-test-key-123" > .env
        echo "DEBUG=True" >> .env
        echo "DB_NAME=asset_db" >> .env
        echo "DB_USER=asset_user" >> .env
        echo "DB_PASSWORD=mysecretpassword" >> .env
        echo "DB_HOST=db" >> .env
        echo "DB_PORT=5432" >> .env

    - name: 4. Linting and formatting code
      run: |
        pip install ruff
        ruff check .
        ruff format --check .
        
    - name: 5. Run docker compose for db and web images
      run: docker compose up -d --build

    - name: 6. Running tests
      run: | 
        docker compose exec -T --user root web coverage run manage.py test
        docker compose exec -T --user root web coverage xml
        # Fix SonarCloud warning - not visible app path
        sed -i "s|<source>/app</source>|<source>${GITHUB_WORKSPACE}</source>|g" coverage.xml
    - name: 6. Code analysis in SonarCloud
      uses: SonarSource/sonarqube-scan-action@9598b8a83feef37de07f549027fab50ecffe6a6e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}