name: Django CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout from repo
      uses: actions/checkout@v4

    - name: 2. Generating .env file
      run: |
        echo "SECRET_KEY=super-secret-test-key-123" > .env
        echo "DEBUG=True" >> .env
        echo "DB_NAME=asset_db" >> .env
        echo "DB_USER=asset_user" >> .env
        echo "DB_PASSWORD=mysecretpassword" >> .env
        echo "DB_HOST=db" >> .env
        echo "DB_PORT=5432" >> .env

    - name: 3. Linting and formatting code
      run: |
        pip install ruff
        ruff check .
        ruff format --check .
        
    - name: 4. Run docker compose for db and web images
      run: docker compose up -d --build

    - name: 5. Delay for postgres run
      run: sleep 10

    - name: 6. Running tests
      run: docker compose exec -T web python manage.py test